# Generated by Django 5.1.2 on 2024-11-03 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNutritionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.IntegerField(default=0)),
                ('total_fat', models.IntegerField(default=0)),
                ('cholesterol', models.IntegerField(default=0)),
                ('sodium', models.IntegerField(default=0)),
                ('carbohydrates', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
                ('calories_limit', models.IntegerField(default=2000)),
                ('total_fat_limit', models.IntegerField(default=78)),
                ('cholesterol_limit', models.IntegerField(default=300)),
                ('sodium_limit', models.IntegerField(default=2300)),
                ('carbohydrates_limit', models.IntegerField(default=275)),
                ('protein_limit', models.IntegerField(default=50)),
                ('selected_goal', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user',)},
            },
        ),
    ]
